version: '3'
services:
  container1:
    image: stain/jena-fuseki
    ports:
      - "3035:3030"
    environment:
      - ADMIN_PASSWORD=pw123
      - FUSEKI_DATASET_1=KG_dataset
    networks:
      - my-network
    restart: "no"

  container2:
    build:
      context: vnc_ubuntu
    ports:
      - "5901:5901"
    networks:
      - my-network
    stdin_open: true
    tty: true
    restart: "no"

  container3:
    image: lfoppiano/grobid:latest-develop
    ports:
      - "8070:8070"
    networks:
      - my-network
    restart: "no"

networks:
  my-network:
    driver: bridge
